// Code generated by ent, DO NOT EDIT.

package entclipmetadata

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the entclipmetadata type in the database.
	Label = "ent_clip_metadata"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFilename holds the string denoting the filename field in the database.
	FieldFilename = "filename"
	// FieldFileURL holds the string denoting the file_url field in the database.
	FieldFileURL = "file_url"
	// FieldFileSize holds the string denoting the file_size field in the database.
	FieldFileSize = "file_size"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldFormat holds the string denoting the format field in the database.
	FieldFormat = "format"
	// FieldWord holds the string denoting the word field in the database.
	FieldWord = "word"
	// FieldSentence holds the string denoting the sentence field in the database.
	FieldSentence = "sentence"
	// FieldThumbnail holds the string denoting the thumbnail field in the database.
	FieldThumbnail = "thumbnail"
	// Table holds the table name of the entclipmetadata in the database.
	Table = "ent_clip_metadata"
)

// Columns holds all SQL columns for entclipmetadata fields.
var Columns = []string{
	FieldID,
	FieldFilename,
	FieldFileURL,
	FieldFileSize,
	FieldDuration,
	FieldFormat,
	FieldWord,
	FieldSentence,
	FieldThumbnail,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	FilenameValidator func(string) error
	// FileURLValidator is a validator for the "file_url" field. It is called by the builders before save.
	FileURLValidator func(string) error
	// FileSizeValidator is a validator for the "file_size" field. It is called by the builders before save.
	FileSizeValidator func(int64) error
	// DurationValidator is a validator for the "duration" field. It is called by the builders before save.
	DurationValidator func(int) error
	// DefaultFormat holds the default value on creation for the "format" field.
	DefaultFormat string
)

// OrderOption defines the ordering options for the EntClipMetadata queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFilename orders the results by the filename field.
func ByFilename(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilename, opts...).ToFunc()
}

// ByFileURL orders the results by the file_url field.
func ByFileURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileURL, opts...).ToFunc()
}

// ByFileSize orders the results by the file_size field.
func ByFileSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSize, opts...).ToFunc()
}

// ByDuration orders the results by the duration field.
func ByDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuration, opts...).ToFunc()
}

// ByFormat orders the results by the format field.
func ByFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormat, opts...).ToFunc()
}

// ByWord orders the results by the word field.
func ByWord(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWord, opts...).ToFunc()
}

// BySentence orders the results by the sentence field.
func BySentence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentence, opts...).ToFunc()
}

// ByThumbnail orders the results by the thumbnail field.
func ByThumbnail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnail, opts...).ToFunc()
}
