package clipserver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"com.gigaboo/clipserver/ent"
	"entgo.io/contrib/entgql"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	return r.client.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	return r.client.Noders(ctx, ids)
}

// EntClipMetadataSlice is the resolver for the entClipMetadataSlice field.
func (r *queryResolver) EntClipMetadataSlice(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int) (*ent.EntClipMetadataConnection, error) {
	return r.client.EntClipMetadata.Query().Paginate(ctx, after, first, before, last)
}

// EntVideoMetadataSlice is the resolver for the entVideoMetadataSlice field.
func (r *queryResolver) EntVideoMetadataSlice(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int) (*ent.EntVideoMetadataConnection, error) {
	return r.client.EntVideoMetadata.Query().Paginate(ctx, after, first, before, last)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
