// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EntClipMetadata is the predicate function for entclipmetadata builders.
type EntClipMetadata func(*sql.Selector)

// EntVideoMetadata is the predicate function for entvideometadata builders.
type EntVideoMetadata func(*sql.Selector)
