// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"com.gigaboo/clipserver/ent/migrate"

	"com.gigaboo/clipserver/ent/entclipmetadata"
	"com.gigaboo/clipserver/ent/entvideometadata"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// EntClipMetadata is the client for interacting with the EntClipMetadata builders.
	EntClipMetadata *EntClipMetadataClient
	// EntVideoMetadata is the client for interacting with the EntVideoMetadata builders.
	EntVideoMetadata *EntVideoMetadataClient
	// additional fields for node api
	tables tables
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.EntClipMetadata = NewEntClipMetadataClient(c.config)
	c.EntVideoMetadata = NewEntVideoMetadataClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		EntClipMetadata:  NewEntClipMetadataClient(cfg),
		EntVideoMetadata: NewEntVideoMetadataClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		EntClipMetadata:  NewEntClipMetadataClient(cfg),
		EntVideoMetadata: NewEntVideoMetadataClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		EntClipMetadata.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.EntClipMetadata.Use(hooks...)
	c.EntVideoMetadata.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.EntClipMetadata.Intercept(interceptors...)
	c.EntVideoMetadata.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *EntClipMetadataMutation:
		return c.EntClipMetadata.mutate(ctx, m)
	case *EntVideoMetadataMutation:
		return c.EntVideoMetadata.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// EntClipMetadataClient is a client for the EntClipMetadata schema.
type EntClipMetadataClient struct {
	config
}

// NewEntClipMetadataClient returns a client for the EntClipMetadata from the given config.
func NewEntClipMetadataClient(c config) *EntClipMetadataClient {
	return &EntClipMetadataClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `entclipmetadata.Hooks(f(g(h())))`.
func (c *EntClipMetadataClient) Use(hooks ...Hook) {
	c.hooks.EntClipMetadata = append(c.hooks.EntClipMetadata, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `entclipmetadata.Intercept(f(g(h())))`.
func (c *EntClipMetadataClient) Intercept(interceptors ...Interceptor) {
	c.inters.EntClipMetadata = append(c.inters.EntClipMetadata, interceptors...)
}

// Create returns a builder for creating a EntClipMetadata entity.
func (c *EntClipMetadataClient) Create() *EntClipMetadataCreate {
	mutation := newEntClipMetadataMutation(c.config, OpCreate)
	return &EntClipMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EntClipMetadata entities.
func (c *EntClipMetadataClient) CreateBulk(builders ...*EntClipMetadataCreate) *EntClipMetadataCreateBulk {
	return &EntClipMetadataCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EntClipMetadataClient) MapCreateBulk(slice any, setFunc func(*EntClipMetadataCreate, int)) *EntClipMetadataCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EntClipMetadataCreateBulk{err: fmt.Errorf("calling to EntClipMetadataClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EntClipMetadataCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EntClipMetadataCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EntClipMetadata.
func (c *EntClipMetadataClient) Update() *EntClipMetadataUpdate {
	mutation := newEntClipMetadataMutation(c.config, OpUpdate)
	return &EntClipMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EntClipMetadataClient) UpdateOne(ecm *EntClipMetadata) *EntClipMetadataUpdateOne {
	mutation := newEntClipMetadataMutation(c.config, OpUpdateOne, withEntClipMetadata(ecm))
	return &EntClipMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EntClipMetadataClient) UpdateOneID(id int) *EntClipMetadataUpdateOne {
	mutation := newEntClipMetadataMutation(c.config, OpUpdateOne, withEntClipMetadataID(id))
	return &EntClipMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EntClipMetadata.
func (c *EntClipMetadataClient) Delete() *EntClipMetadataDelete {
	mutation := newEntClipMetadataMutation(c.config, OpDelete)
	return &EntClipMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EntClipMetadataClient) DeleteOne(ecm *EntClipMetadata) *EntClipMetadataDeleteOne {
	return c.DeleteOneID(ecm.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EntClipMetadataClient) DeleteOneID(id int) *EntClipMetadataDeleteOne {
	builder := c.Delete().Where(entclipmetadata.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EntClipMetadataDeleteOne{builder}
}

// Query returns a query builder for EntClipMetadata.
func (c *EntClipMetadataClient) Query() *EntClipMetadataQuery {
	return &EntClipMetadataQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEntClipMetadata},
		inters: c.Interceptors(),
	}
}

// Get returns a EntClipMetadata entity by its id.
func (c *EntClipMetadataClient) Get(ctx context.Context, id int) (*EntClipMetadata, error) {
	return c.Query().Where(entclipmetadata.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EntClipMetadataClient) GetX(ctx context.Context, id int) *EntClipMetadata {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EntClipMetadataClient) Hooks() []Hook {
	return c.hooks.EntClipMetadata
}

// Interceptors returns the client interceptors.
func (c *EntClipMetadataClient) Interceptors() []Interceptor {
	return c.inters.EntClipMetadata
}

func (c *EntClipMetadataClient) mutate(ctx context.Context, m *EntClipMetadataMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EntClipMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EntClipMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EntClipMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EntClipMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EntClipMetadata mutation op: %q", m.Op())
	}
}

// EntVideoMetadataClient is a client for the EntVideoMetadata schema.
type EntVideoMetadataClient struct {
	config
}

// NewEntVideoMetadataClient returns a client for the EntVideoMetadata from the given config.
func NewEntVideoMetadataClient(c config) *EntVideoMetadataClient {
	return &EntVideoMetadataClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `entvideometadata.Hooks(f(g(h())))`.
func (c *EntVideoMetadataClient) Use(hooks ...Hook) {
	c.hooks.EntVideoMetadata = append(c.hooks.EntVideoMetadata, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `entvideometadata.Intercept(f(g(h())))`.
func (c *EntVideoMetadataClient) Intercept(interceptors ...Interceptor) {
	c.inters.EntVideoMetadata = append(c.inters.EntVideoMetadata, interceptors...)
}

// Create returns a builder for creating a EntVideoMetadata entity.
func (c *EntVideoMetadataClient) Create() *EntVideoMetadataCreate {
	mutation := newEntVideoMetadataMutation(c.config, OpCreate)
	return &EntVideoMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EntVideoMetadata entities.
func (c *EntVideoMetadataClient) CreateBulk(builders ...*EntVideoMetadataCreate) *EntVideoMetadataCreateBulk {
	return &EntVideoMetadataCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EntVideoMetadataClient) MapCreateBulk(slice any, setFunc func(*EntVideoMetadataCreate, int)) *EntVideoMetadataCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EntVideoMetadataCreateBulk{err: fmt.Errorf("calling to EntVideoMetadataClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EntVideoMetadataCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EntVideoMetadataCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EntVideoMetadata.
func (c *EntVideoMetadataClient) Update() *EntVideoMetadataUpdate {
	mutation := newEntVideoMetadataMutation(c.config, OpUpdate)
	return &EntVideoMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EntVideoMetadataClient) UpdateOne(evm *EntVideoMetadata) *EntVideoMetadataUpdateOne {
	mutation := newEntVideoMetadataMutation(c.config, OpUpdateOne, withEntVideoMetadata(evm))
	return &EntVideoMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EntVideoMetadataClient) UpdateOneID(id int) *EntVideoMetadataUpdateOne {
	mutation := newEntVideoMetadataMutation(c.config, OpUpdateOne, withEntVideoMetadataID(id))
	return &EntVideoMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EntVideoMetadata.
func (c *EntVideoMetadataClient) Delete() *EntVideoMetadataDelete {
	mutation := newEntVideoMetadataMutation(c.config, OpDelete)
	return &EntVideoMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EntVideoMetadataClient) DeleteOne(evm *EntVideoMetadata) *EntVideoMetadataDeleteOne {
	return c.DeleteOneID(evm.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EntVideoMetadataClient) DeleteOneID(id int) *EntVideoMetadataDeleteOne {
	builder := c.Delete().Where(entvideometadata.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EntVideoMetadataDeleteOne{builder}
}

// Query returns a query builder for EntVideoMetadata.
func (c *EntVideoMetadataClient) Query() *EntVideoMetadataQuery {
	return &EntVideoMetadataQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEntVideoMetadata},
		inters: c.Interceptors(),
	}
}

// Get returns a EntVideoMetadata entity by its id.
func (c *EntVideoMetadataClient) Get(ctx context.Context, id int) (*EntVideoMetadata, error) {
	return c.Query().Where(entvideometadata.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EntVideoMetadataClient) GetX(ctx context.Context, id int) *EntVideoMetadata {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EntVideoMetadataClient) Hooks() []Hook {
	return c.hooks.EntVideoMetadata
}

// Interceptors returns the client interceptors.
func (c *EntVideoMetadataClient) Interceptors() []Interceptor {
	return c.inters.EntVideoMetadata
}

func (c *EntVideoMetadataClient) mutate(ctx context.Context, m *EntVideoMetadataMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EntVideoMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EntVideoMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EntVideoMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EntVideoMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EntVideoMetadata mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		EntClipMetadata, EntVideoMetadata []ent.Hook
	}
	inters struct {
		EntClipMetadata, EntVideoMetadata []ent.Interceptor
	}
)
