// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"com.gigaboo/clipserver/ent/entclipmetadata"
	"com.gigaboo/clipserver/ent/predicate"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntClipMetadataQuery is the builder for querying EntClipMetadata entities.
type EntClipMetadataQuery struct {
	config
	ctx        *QueryContext
	order      []entclipmetadata.OrderOption
	inters     []Interceptor
	predicates []predicate.EntClipMetadata
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*EntClipMetadata) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntClipMetadataQuery builder.
func (ecmq *EntClipMetadataQuery) Where(ps ...predicate.EntClipMetadata) *EntClipMetadataQuery {
	ecmq.predicates = append(ecmq.predicates, ps...)
	return ecmq
}

// Limit the number of records to be returned by this query.
func (ecmq *EntClipMetadataQuery) Limit(limit int) *EntClipMetadataQuery {
	ecmq.ctx.Limit = &limit
	return ecmq
}

// Offset to start from.
func (ecmq *EntClipMetadataQuery) Offset(offset int) *EntClipMetadataQuery {
	ecmq.ctx.Offset = &offset
	return ecmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ecmq *EntClipMetadataQuery) Unique(unique bool) *EntClipMetadataQuery {
	ecmq.ctx.Unique = &unique
	return ecmq
}

// Order specifies how the records should be ordered.
func (ecmq *EntClipMetadataQuery) Order(o ...entclipmetadata.OrderOption) *EntClipMetadataQuery {
	ecmq.order = append(ecmq.order, o...)
	return ecmq
}

// First returns the first EntClipMetadata entity from the query.
// Returns a *NotFoundError when no EntClipMetadata was found.
func (ecmq *EntClipMetadataQuery) First(ctx context.Context) (*EntClipMetadata, error) {
	nodes, err := ecmq.Limit(1).All(setContextOp(ctx, ecmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entclipmetadata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ecmq *EntClipMetadataQuery) FirstX(ctx context.Context) *EntClipMetadata {
	node, err := ecmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntClipMetadata ID from the query.
// Returns a *NotFoundError when no EntClipMetadata ID was found.
func (ecmq *EntClipMetadataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ecmq.Limit(1).IDs(setContextOp(ctx, ecmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entclipmetadata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ecmq *EntClipMetadataQuery) FirstIDX(ctx context.Context) int {
	id, err := ecmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntClipMetadata entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntClipMetadata entity is found.
// Returns a *NotFoundError when no EntClipMetadata entities are found.
func (ecmq *EntClipMetadataQuery) Only(ctx context.Context) (*EntClipMetadata, error) {
	nodes, err := ecmq.Limit(2).All(setContextOp(ctx, ecmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entclipmetadata.Label}
	default:
		return nil, &NotSingularError{entclipmetadata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ecmq *EntClipMetadataQuery) OnlyX(ctx context.Context) *EntClipMetadata {
	node, err := ecmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntClipMetadata ID in the query.
// Returns a *NotSingularError when more than one EntClipMetadata ID is found.
// Returns a *NotFoundError when no entities are found.
func (ecmq *EntClipMetadataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ecmq.Limit(2).IDs(setContextOp(ctx, ecmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entclipmetadata.Label}
	default:
		err = &NotSingularError{entclipmetadata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ecmq *EntClipMetadataQuery) OnlyIDX(ctx context.Context) int {
	id, err := ecmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntClipMetadataSlice.
func (ecmq *EntClipMetadataQuery) All(ctx context.Context) ([]*EntClipMetadata, error) {
	ctx = setContextOp(ctx, ecmq.ctx, ent.OpQueryAll)
	if err := ecmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntClipMetadata, *EntClipMetadataQuery]()
	return withInterceptors[[]*EntClipMetadata](ctx, ecmq, qr, ecmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ecmq *EntClipMetadataQuery) AllX(ctx context.Context) []*EntClipMetadata {
	nodes, err := ecmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntClipMetadata IDs.
func (ecmq *EntClipMetadataQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ecmq.ctx.Unique == nil && ecmq.path != nil {
		ecmq.Unique(true)
	}
	ctx = setContextOp(ctx, ecmq.ctx, ent.OpQueryIDs)
	if err = ecmq.Select(entclipmetadata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ecmq *EntClipMetadataQuery) IDsX(ctx context.Context) []int {
	ids, err := ecmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ecmq *EntClipMetadataQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ecmq.ctx, ent.OpQueryCount)
	if err := ecmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ecmq, querierCount[*EntClipMetadataQuery](), ecmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ecmq *EntClipMetadataQuery) CountX(ctx context.Context) int {
	count, err := ecmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ecmq *EntClipMetadataQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ecmq.ctx, ent.OpQueryExist)
	switch _, err := ecmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ecmq *EntClipMetadataQuery) ExistX(ctx context.Context) bool {
	exist, err := ecmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntClipMetadataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ecmq *EntClipMetadataQuery) Clone() *EntClipMetadataQuery {
	if ecmq == nil {
		return nil
	}
	return &EntClipMetadataQuery{
		config:     ecmq.config,
		ctx:        ecmq.ctx.Clone(),
		order:      append([]entclipmetadata.OrderOption{}, ecmq.order...),
		inters:     append([]Interceptor{}, ecmq.inters...),
		predicates: append([]predicate.EntClipMetadata{}, ecmq.predicates...),
		// clone intermediate query.
		sql:  ecmq.sql.Clone(),
		path: ecmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Filename string `json:"filename,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntClipMetadata.Query().
//		GroupBy(entclipmetadata.FieldFilename).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ecmq *EntClipMetadataQuery) GroupBy(field string, fields ...string) *EntClipMetadataGroupBy {
	ecmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntClipMetadataGroupBy{build: ecmq}
	grbuild.flds = &ecmq.ctx.Fields
	grbuild.label = entclipmetadata.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Filename string `json:"filename,omitempty"`
//	}
//
//	client.EntClipMetadata.Query().
//		Select(entclipmetadata.FieldFilename).
//		Scan(ctx, &v)
func (ecmq *EntClipMetadataQuery) Select(fields ...string) *EntClipMetadataSelect {
	ecmq.ctx.Fields = append(ecmq.ctx.Fields, fields...)
	sbuild := &EntClipMetadataSelect{EntClipMetadataQuery: ecmq}
	sbuild.label = entclipmetadata.Label
	sbuild.flds, sbuild.scan = &ecmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntClipMetadataSelect configured with the given aggregations.
func (ecmq *EntClipMetadataQuery) Aggregate(fns ...AggregateFunc) *EntClipMetadataSelect {
	return ecmq.Select().Aggregate(fns...)
}

func (ecmq *EntClipMetadataQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ecmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ecmq); err != nil {
				return err
			}
		}
	}
	for _, f := range ecmq.ctx.Fields {
		if !entclipmetadata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ecmq.path != nil {
		prev, err := ecmq.path(ctx)
		if err != nil {
			return err
		}
		ecmq.sql = prev
	}
	return nil
}

func (ecmq *EntClipMetadataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntClipMetadata, error) {
	var (
		nodes = []*EntClipMetadata{}
		_spec = ecmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntClipMetadata).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntClipMetadata{config: ecmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ecmq.modifiers) > 0 {
		_spec.Modifiers = ecmq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ecmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range ecmq.loadTotal {
		if err := ecmq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ecmq *EntClipMetadataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ecmq.querySpec()
	if len(ecmq.modifiers) > 0 {
		_spec.Modifiers = ecmq.modifiers
	}
	_spec.Node.Columns = ecmq.ctx.Fields
	if len(ecmq.ctx.Fields) > 0 {
		_spec.Unique = ecmq.ctx.Unique != nil && *ecmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ecmq.driver, _spec)
}

func (ecmq *EntClipMetadataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(entclipmetadata.Table, entclipmetadata.Columns, sqlgraph.NewFieldSpec(entclipmetadata.FieldID, field.TypeInt))
	_spec.From = ecmq.sql
	if unique := ecmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ecmq.path != nil {
		_spec.Unique = true
	}
	if fields := ecmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entclipmetadata.FieldID)
		for i := range fields {
			if fields[i] != entclipmetadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ecmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ecmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ecmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ecmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ecmq *EntClipMetadataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ecmq.driver.Dialect())
	t1 := builder.Table(entclipmetadata.Table)
	columns := ecmq.ctx.Fields
	if len(columns) == 0 {
		columns = entclipmetadata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ecmq.sql != nil {
		selector = ecmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ecmq.ctx.Unique != nil && *ecmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ecmq.predicates {
		p(selector)
	}
	for _, p := range ecmq.order {
		p(selector)
	}
	if offset := ecmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ecmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntClipMetadataGroupBy is the group-by builder for EntClipMetadata entities.
type EntClipMetadataGroupBy struct {
	selector
	build *EntClipMetadataQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ecmgb *EntClipMetadataGroupBy) Aggregate(fns ...AggregateFunc) *EntClipMetadataGroupBy {
	ecmgb.fns = append(ecmgb.fns, fns...)
	return ecmgb
}

// Scan applies the selector query and scans the result into the given value.
func (ecmgb *EntClipMetadataGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ecmgb.build.ctx, ent.OpQueryGroupBy)
	if err := ecmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntClipMetadataQuery, *EntClipMetadataGroupBy](ctx, ecmgb.build, ecmgb, ecmgb.build.inters, v)
}

func (ecmgb *EntClipMetadataGroupBy) sqlScan(ctx context.Context, root *EntClipMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ecmgb.fns))
	for _, fn := range ecmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ecmgb.flds)+len(ecmgb.fns))
		for _, f := range *ecmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ecmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ecmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntClipMetadataSelect is the builder for selecting fields of EntClipMetadata entities.
type EntClipMetadataSelect struct {
	*EntClipMetadataQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ecms *EntClipMetadataSelect) Aggregate(fns ...AggregateFunc) *EntClipMetadataSelect {
	ecms.fns = append(ecms.fns, fns...)
	return ecms
}

// Scan applies the selector query and scans the result into the given value.
func (ecms *EntClipMetadataSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ecms.ctx, ent.OpQuerySelect)
	if err := ecms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntClipMetadataQuery, *EntClipMetadataSelect](ctx, ecms.EntClipMetadataQuery, ecms, ecms.inters, v)
}

func (ecms *EntClipMetadataSelect) sqlScan(ctx context.Context, root *EntClipMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ecms.fns))
	for _, fn := range ecms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ecms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ecms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
