// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"com.gigaboo/clipserver/ent/entvideometadata"
	"com.gigaboo/clipserver/ent/predicate"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntVideoMetadataQuery is the builder for querying EntVideoMetadata entities.
type EntVideoMetadataQuery struct {
	config
	ctx        *QueryContext
	order      []entvideometadata.OrderOption
	inters     []Interceptor
	predicates []predicate.EntVideoMetadata
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*EntVideoMetadata) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntVideoMetadataQuery builder.
func (evmq *EntVideoMetadataQuery) Where(ps ...predicate.EntVideoMetadata) *EntVideoMetadataQuery {
	evmq.predicates = append(evmq.predicates, ps...)
	return evmq
}

// Limit the number of records to be returned by this query.
func (evmq *EntVideoMetadataQuery) Limit(limit int) *EntVideoMetadataQuery {
	evmq.ctx.Limit = &limit
	return evmq
}

// Offset to start from.
func (evmq *EntVideoMetadataQuery) Offset(offset int) *EntVideoMetadataQuery {
	evmq.ctx.Offset = &offset
	return evmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (evmq *EntVideoMetadataQuery) Unique(unique bool) *EntVideoMetadataQuery {
	evmq.ctx.Unique = &unique
	return evmq
}

// Order specifies how the records should be ordered.
func (evmq *EntVideoMetadataQuery) Order(o ...entvideometadata.OrderOption) *EntVideoMetadataQuery {
	evmq.order = append(evmq.order, o...)
	return evmq
}

// First returns the first EntVideoMetadata entity from the query.
// Returns a *NotFoundError when no EntVideoMetadata was found.
func (evmq *EntVideoMetadataQuery) First(ctx context.Context) (*EntVideoMetadata, error) {
	nodes, err := evmq.Limit(1).All(setContextOp(ctx, evmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entvideometadata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (evmq *EntVideoMetadataQuery) FirstX(ctx context.Context) *EntVideoMetadata {
	node, err := evmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntVideoMetadata ID from the query.
// Returns a *NotFoundError when no EntVideoMetadata ID was found.
func (evmq *EntVideoMetadataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = evmq.Limit(1).IDs(setContextOp(ctx, evmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entvideometadata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (evmq *EntVideoMetadataQuery) FirstIDX(ctx context.Context) int {
	id, err := evmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntVideoMetadata entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntVideoMetadata entity is found.
// Returns a *NotFoundError when no EntVideoMetadata entities are found.
func (evmq *EntVideoMetadataQuery) Only(ctx context.Context) (*EntVideoMetadata, error) {
	nodes, err := evmq.Limit(2).All(setContextOp(ctx, evmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entvideometadata.Label}
	default:
		return nil, &NotSingularError{entvideometadata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (evmq *EntVideoMetadataQuery) OnlyX(ctx context.Context) *EntVideoMetadata {
	node, err := evmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntVideoMetadata ID in the query.
// Returns a *NotSingularError when more than one EntVideoMetadata ID is found.
// Returns a *NotFoundError when no entities are found.
func (evmq *EntVideoMetadataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = evmq.Limit(2).IDs(setContextOp(ctx, evmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entvideometadata.Label}
	default:
		err = &NotSingularError{entvideometadata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (evmq *EntVideoMetadataQuery) OnlyIDX(ctx context.Context) int {
	id, err := evmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntVideoMetadataSlice.
func (evmq *EntVideoMetadataQuery) All(ctx context.Context) ([]*EntVideoMetadata, error) {
	ctx = setContextOp(ctx, evmq.ctx, ent.OpQueryAll)
	if err := evmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntVideoMetadata, *EntVideoMetadataQuery]()
	return withInterceptors[[]*EntVideoMetadata](ctx, evmq, qr, evmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (evmq *EntVideoMetadataQuery) AllX(ctx context.Context) []*EntVideoMetadata {
	nodes, err := evmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntVideoMetadata IDs.
func (evmq *EntVideoMetadataQuery) IDs(ctx context.Context) (ids []int, err error) {
	if evmq.ctx.Unique == nil && evmq.path != nil {
		evmq.Unique(true)
	}
	ctx = setContextOp(ctx, evmq.ctx, ent.OpQueryIDs)
	if err = evmq.Select(entvideometadata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (evmq *EntVideoMetadataQuery) IDsX(ctx context.Context) []int {
	ids, err := evmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (evmq *EntVideoMetadataQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, evmq.ctx, ent.OpQueryCount)
	if err := evmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, evmq, querierCount[*EntVideoMetadataQuery](), evmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (evmq *EntVideoMetadataQuery) CountX(ctx context.Context) int {
	count, err := evmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (evmq *EntVideoMetadataQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, evmq.ctx, ent.OpQueryExist)
	switch _, err := evmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (evmq *EntVideoMetadataQuery) ExistX(ctx context.Context) bool {
	exist, err := evmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntVideoMetadataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (evmq *EntVideoMetadataQuery) Clone() *EntVideoMetadataQuery {
	if evmq == nil {
		return nil
	}
	return &EntVideoMetadataQuery{
		config:     evmq.config,
		ctx:        evmq.ctx.Clone(),
		order:      append([]entvideometadata.OrderOption{}, evmq.order...),
		inters:     append([]Interceptor{}, evmq.inters...),
		predicates: append([]predicate.EntVideoMetadata{}, evmq.predicates...),
		// clone intermediate query.
		sql:  evmq.sql.Clone(),
		path: evmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntVideoMetadata.Query().
//		GroupBy(entvideometadata.FieldURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (evmq *EntVideoMetadataQuery) GroupBy(field string, fields ...string) *EntVideoMetadataGroupBy {
	evmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntVideoMetadataGroupBy{build: evmq}
	grbuild.flds = &evmq.ctx.Fields
	grbuild.label = entvideometadata.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//	}
//
//	client.EntVideoMetadata.Query().
//		Select(entvideometadata.FieldURL).
//		Scan(ctx, &v)
func (evmq *EntVideoMetadataQuery) Select(fields ...string) *EntVideoMetadataSelect {
	evmq.ctx.Fields = append(evmq.ctx.Fields, fields...)
	sbuild := &EntVideoMetadataSelect{EntVideoMetadataQuery: evmq}
	sbuild.label = entvideometadata.Label
	sbuild.flds, sbuild.scan = &evmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntVideoMetadataSelect configured with the given aggregations.
func (evmq *EntVideoMetadataQuery) Aggregate(fns ...AggregateFunc) *EntVideoMetadataSelect {
	return evmq.Select().Aggregate(fns...)
}

func (evmq *EntVideoMetadataQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range evmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, evmq); err != nil {
				return err
			}
		}
	}
	for _, f := range evmq.ctx.Fields {
		if !entvideometadata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if evmq.path != nil {
		prev, err := evmq.path(ctx)
		if err != nil {
			return err
		}
		evmq.sql = prev
	}
	return nil
}

func (evmq *EntVideoMetadataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntVideoMetadata, error) {
	var (
		nodes = []*EntVideoMetadata{}
		_spec = evmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntVideoMetadata).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntVideoMetadata{config: evmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(evmq.modifiers) > 0 {
		_spec.Modifiers = evmq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, evmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range evmq.loadTotal {
		if err := evmq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (evmq *EntVideoMetadataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := evmq.querySpec()
	if len(evmq.modifiers) > 0 {
		_spec.Modifiers = evmq.modifiers
	}
	_spec.Node.Columns = evmq.ctx.Fields
	if len(evmq.ctx.Fields) > 0 {
		_spec.Unique = evmq.ctx.Unique != nil && *evmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, evmq.driver, _spec)
}

func (evmq *EntVideoMetadataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(entvideometadata.Table, entvideometadata.Columns, sqlgraph.NewFieldSpec(entvideometadata.FieldID, field.TypeInt))
	_spec.From = evmq.sql
	if unique := evmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if evmq.path != nil {
		_spec.Unique = true
	}
	if fields := evmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entvideometadata.FieldID)
		for i := range fields {
			if fields[i] != entvideometadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := evmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := evmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := evmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := evmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (evmq *EntVideoMetadataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(evmq.driver.Dialect())
	t1 := builder.Table(entvideometadata.Table)
	columns := evmq.ctx.Fields
	if len(columns) == 0 {
		columns = entvideometadata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if evmq.sql != nil {
		selector = evmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if evmq.ctx.Unique != nil && *evmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range evmq.predicates {
		p(selector)
	}
	for _, p := range evmq.order {
		p(selector)
	}
	if offset := evmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := evmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntVideoMetadataGroupBy is the group-by builder for EntVideoMetadata entities.
type EntVideoMetadataGroupBy struct {
	selector
	build *EntVideoMetadataQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (evmgb *EntVideoMetadataGroupBy) Aggregate(fns ...AggregateFunc) *EntVideoMetadataGroupBy {
	evmgb.fns = append(evmgb.fns, fns...)
	return evmgb
}

// Scan applies the selector query and scans the result into the given value.
func (evmgb *EntVideoMetadataGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, evmgb.build.ctx, ent.OpQueryGroupBy)
	if err := evmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntVideoMetadataQuery, *EntVideoMetadataGroupBy](ctx, evmgb.build, evmgb, evmgb.build.inters, v)
}

func (evmgb *EntVideoMetadataGroupBy) sqlScan(ctx context.Context, root *EntVideoMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(evmgb.fns))
	for _, fn := range evmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*evmgb.flds)+len(evmgb.fns))
		for _, f := range *evmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*evmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := evmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntVideoMetadataSelect is the builder for selecting fields of EntVideoMetadata entities.
type EntVideoMetadataSelect struct {
	*EntVideoMetadataQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (evms *EntVideoMetadataSelect) Aggregate(fns ...AggregateFunc) *EntVideoMetadataSelect {
	evms.fns = append(evms.fns, fns...)
	return evms
}

// Scan applies the selector query and scans the result into the given value.
func (evms *EntVideoMetadataSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, evms.ctx, ent.OpQuerySelect)
	if err := evms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntVideoMetadataQuery, *EntVideoMetadataSelect](ctx, evms.EntVideoMetadataQuery, evms, evms.inters, v)
}

func (evms *EntVideoMetadataSelect) sqlScan(ctx context.Context, root *EntVideoMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(evms.fns))
	for _, fn := range evms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*evms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := evms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
