// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"com.gigaboo/clipserver/ent/entclipmetadata"
	"com.gigaboo/clipserver/ent/entvideometadata"
	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (ecm *EntClipMetadataQuery) CollectFields(ctx context.Context, satisfies ...string) (*EntClipMetadataQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return ecm, nil
	}
	if err := ecm.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return ecm, nil
}

func (ecm *EntClipMetadataQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(entclipmetadata.Columns))
		selectedFields = []string{entclipmetadata.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "jobID":
			if _, ok := fieldSeen[entclipmetadata.FieldJobID]; !ok {
				selectedFields = append(selectedFields, entclipmetadata.FieldJobID)
				fieldSeen[entclipmetadata.FieldJobID] = struct{}{}
			}
		case "filename":
			if _, ok := fieldSeen[entclipmetadata.FieldFilename]; !ok {
				selectedFields = append(selectedFields, entclipmetadata.FieldFilename)
				fieldSeen[entclipmetadata.FieldFilename] = struct{}{}
			}
		case "fileURL":
			if _, ok := fieldSeen[entclipmetadata.FieldFileURL]; !ok {
				selectedFields = append(selectedFields, entclipmetadata.FieldFileURL)
				fieldSeen[entclipmetadata.FieldFileURL] = struct{}{}
			}
		case "fileSize":
			if _, ok := fieldSeen[entclipmetadata.FieldFileSize]; !ok {
				selectedFields = append(selectedFields, entclipmetadata.FieldFileSize)
				fieldSeen[entclipmetadata.FieldFileSize] = struct{}{}
			}
		case "duration":
			if _, ok := fieldSeen[entclipmetadata.FieldDuration]; !ok {
				selectedFields = append(selectedFields, entclipmetadata.FieldDuration)
				fieldSeen[entclipmetadata.FieldDuration] = struct{}{}
			}
		case "format":
			if _, ok := fieldSeen[entclipmetadata.FieldFormat]; !ok {
				selectedFields = append(selectedFields, entclipmetadata.FieldFormat)
				fieldSeen[entclipmetadata.FieldFormat] = struct{}{}
			}
		case "resolution":
			if _, ok := fieldSeen[entclipmetadata.FieldResolution]; !ok {
				selectedFields = append(selectedFields, entclipmetadata.FieldResolution)
				fieldSeen[entclipmetadata.FieldResolution] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		ecm.Select(selectedFields...)
	}
	return nil
}

type entclipmetadataPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []EntClipMetadataPaginateOption
}

func newEntClipMetadataPaginateArgs(rv map[string]any) *entclipmetadataPaginateArgs {
	args := &entclipmetadataPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (evm *EntVideoMetadataQuery) CollectFields(ctx context.Context, satisfies ...string) (*EntVideoMetadataQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return evm, nil
	}
	if err := evm.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return evm, nil
}

func (evm *EntVideoMetadataQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(entvideometadata.Columns))
		selectedFields = []string{entvideometadata.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "url":
			if _, ok := fieldSeen[entvideometadata.FieldURL]; !ok {
				selectedFields = append(selectedFields, entvideometadata.FieldURL)
				fieldSeen[entvideometadata.FieldURL] = struct{}{}
			}
		case "filename":
			if _, ok := fieldSeen[entvideometadata.FieldFilename]; !ok {
				selectedFields = append(selectedFields, entvideometadata.FieldFilename)
				fieldSeen[entvideometadata.FieldFilename] = struct{}{}
			}
		case "fileSize":
			if _, ok := fieldSeen[entvideometadata.FieldFileSize]; !ok {
				selectedFields = append(selectedFields, entvideometadata.FieldFileSize)
				fieldSeen[entvideometadata.FieldFileSize] = struct{}{}
			}
		case "contentType":
			if _, ok := fieldSeen[entvideometadata.FieldContentType]; !ok {
				selectedFields = append(selectedFields, entvideometadata.FieldContentType)
				fieldSeen[entvideometadata.FieldContentType] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		evm.Select(selectedFields...)
	}
	return nil
}

type entvideometadataPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []EntVideoMetadataPaginateOption
}

func newEntVideoMetadataPaginateArgs(rv map[string]any) *entvideometadataPaginateArgs {
	args := &entvideometadataPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
