// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"com.gigaboo/clipserver/ent/entclipmetadata"
	"com.gigaboo/clipserver/ent/entvideometadata"
	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// EntClipMetadataEdge is the edge representation of EntClipMetadata.
type EntClipMetadataEdge struct {
	Node   *EntClipMetadata `json:"node"`
	Cursor Cursor           `json:"cursor"`
}

// EntClipMetadataConnection is the connection containing edges to EntClipMetadata.
type EntClipMetadataConnection struct {
	Edges      []*EntClipMetadataEdge `json:"edges"`
	PageInfo   PageInfo               `json:"pageInfo"`
	TotalCount int                    `json:"totalCount"`
}

func (c *EntClipMetadataConnection) build(nodes []*EntClipMetadata, pager *entclipmetadataPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *EntClipMetadata
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *EntClipMetadata {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *EntClipMetadata {
			return nodes[i]
		}
	}
	c.Edges = make([]*EntClipMetadataEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &EntClipMetadataEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// EntClipMetadataPaginateOption enables pagination customization.
type EntClipMetadataPaginateOption func(*entclipmetadataPager) error

// WithEntClipMetadataOrder configures pagination ordering.
func WithEntClipMetadataOrder(order *EntClipMetadataOrder) EntClipMetadataPaginateOption {
	if order == nil {
		order = DefaultEntClipMetadataOrder
	}
	o := *order
	return func(pager *entclipmetadataPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultEntClipMetadataOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithEntClipMetadataFilter configures pagination filter.
func WithEntClipMetadataFilter(filter func(*EntClipMetadataQuery) (*EntClipMetadataQuery, error)) EntClipMetadataPaginateOption {
	return func(pager *entclipmetadataPager) error {
		if filter == nil {
			return errors.New("EntClipMetadataQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type entclipmetadataPager struct {
	reverse bool
	order   *EntClipMetadataOrder
	filter  func(*EntClipMetadataQuery) (*EntClipMetadataQuery, error)
}

func newEntClipMetadataPager(opts []EntClipMetadataPaginateOption, reverse bool) (*entclipmetadataPager, error) {
	pager := &entclipmetadataPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultEntClipMetadataOrder
	}
	return pager, nil
}

func (p *entclipmetadataPager) applyFilter(query *EntClipMetadataQuery) (*EntClipMetadataQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *entclipmetadataPager) toCursor(ecm *EntClipMetadata) Cursor {
	return p.order.Field.toCursor(ecm)
}

func (p *entclipmetadataPager) applyCursors(query *EntClipMetadataQuery, after, before *Cursor) (*EntClipMetadataQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultEntClipMetadataOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *entclipmetadataPager) applyOrder(query *EntClipMetadataQuery) *EntClipMetadataQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultEntClipMetadataOrder.Field {
		query = query.Order(DefaultEntClipMetadataOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *entclipmetadataPager) orderExpr(query *EntClipMetadataQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultEntClipMetadataOrder.Field {
			b.Comma().Ident(DefaultEntClipMetadataOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to EntClipMetadata.
func (ecm *EntClipMetadataQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...EntClipMetadataPaginateOption,
) (*EntClipMetadataConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newEntClipMetadataPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if ecm, err = pager.applyFilter(ecm); err != nil {
		return nil, err
	}
	conn := &EntClipMetadataConnection{Edges: []*EntClipMetadataEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := ecm.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if ecm, err = pager.applyCursors(ecm, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		ecm.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := ecm.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	ecm = pager.applyOrder(ecm)
	nodes, err := ecm.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// EntClipMetadataOrderField defines the ordering field of EntClipMetadata.
type EntClipMetadataOrderField struct {
	// Value extracts the ordering value from the given EntClipMetadata.
	Value    func(*EntClipMetadata) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) entclipmetadata.OrderOption
	toCursor func(*EntClipMetadata) Cursor
}

// EntClipMetadataOrder defines the ordering of EntClipMetadata.
type EntClipMetadataOrder struct {
	Direction OrderDirection             `json:"direction"`
	Field     *EntClipMetadataOrderField `json:"field"`
}

// DefaultEntClipMetadataOrder is the default ordering of EntClipMetadata.
var DefaultEntClipMetadataOrder = &EntClipMetadataOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &EntClipMetadataOrderField{
		Value: func(ecm *EntClipMetadata) (ent.Value, error) {
			return ecm.ID, nil
		},
		column: entclipmetadata.FieldID,
		toTerm: entclipmetadata.ByID,
		toCursor: func(ecm *EntClipMetadata) Cursor {
			return Cursor{ID: ecm.ID}
		},
	},
}

// ToEdge converts EntClipMetadata into EntClipMetadataEdge.
func (ecm *EntClipMetadata) ToEdge(order *EntClipMetadataOrder) *EntClipMetadataEdge {
	if order == nil {
		order = DefaultEntClipMetadataOrder
	}
	return &EntClipMetadataEdge{
		Node:   ecm,
		Cursor: order.Field.toCursor(ecm),
	}
}

// EntVideoMetadataEdge is the edge representation of EntVideoMetadata.
type EntVideoMetadataEdge struct {
	Node   *EntVideoMetadata `json:"node"`
	Cursor Cursor            `json:"cursor"`
}

// EntVideoMetadataConnection is the connection containing edges to EntVideoMetadata.
type EntVideoMetadataConnection struct {
	Edges      []*EntVideoMetadataEdge `json:"edges"`
	PageInfo   PageInfo                `json:"pageInfo"`
	TotalCount int                     `json:"totalCount"`
}

func (c *EntVideoMetadataConnection) build(nodes []*EntVideoMetadata, pager *entvideometadataPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *EntVideoMetadata
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *EntVideoMetadata {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *EntVideoMetadata {
			return nodes[i]
		}
	}
	c.Edges = make([]*EntVideoMetadataEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &EntVideoMetadataEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// EntVideoMetadataPaginateOption enables pagination customization.
type EntVideoMetadataPaginateOption func(*entvideometadataPager) error

// WithEntVideoMetadataOrder configures pagination ordering.
func WithEntVideoMetadataOrder(order *EntVideoMetadataOrder) EntVideoMetadataPaginateOption {
	if order == nil {
		order = DefaultEntVideoMetadataOrder
	}
	o := *order
	return func(pager *entvideometadataPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultEntVideoMetadataOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithEntVideoMetadataFilter configures pagination filter.
func WithEntVideoMetadataFilter(filter func(*EntVideoMetadataQuery) (*EntVideoMetadataQuery, error)) EntVideoMetadataPaginateOption {
	return func(pager *entvideometadataPager) error {
		if filter == nil {
			return errors.New("EntVideoMetadataQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type entvideometadataPager struct {
	reverse bool
	order   *EntVideoMetadataOrder
	filter  func(*EntVideoMetadataQuery) (*EntVideoMetadataQuery, error)
}

func newEntVideoMetadataPager(opts []EntVideoMetadataPaginateOption, reverse bool) (*entvideometadataPager, error) {
	pager := &entvideometadataPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultEntVideoMetadataOrder
	}
	return pager, nil
}

func (p *entvideometadataPager) applyFilter(query *EntVideoMetadataQuery) (*EntVideoMetadataQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *entvideometadataPager) toCursor(evm *EntVideoMetadata) Cursor {
	return p.order.Field.toCursor(evm)
}

func (p *entvideometadataPager) applyCursors(query *EntVideoMetadataQuery, after, before *Cursor) (*EntVideoMetadataQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultEntVideoMetadataOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *entvideometadataPager) applyOrder(query *EntVideoMetadataQuery) *EntVideoMetadataQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultEntVideoMetadataOrder.Field {
		query = query.Order(DefaultEntVideoMetadataOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *entvideometadataPager) orderExpr(query *EntVideoMetadataQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultEntVideoMetadataOrder.Field {
			b.Comma().Ident(DefaultEntVideoMetadataOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to EntVideoMetadata.
func (evm *EntVideoMetadataQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...EntVideoMetadataPaginateOption,
) (*EntVideoMetadataConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newEntVideoMetadataPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if evm, err = pager.applyFilter(evm); err != nil {
		return nil, err
	}
	conn := &EntVideoMetadataConnection{Edges: []*EntVideoMetadataEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := evm.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if evm, err = pager.applyCursors(evm, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		evm.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := evm.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	evm = pager.applyOrder(evm)
	nodes, err := evm.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// EntVideoMetadataOrderField defines the ordering field of EntVideoMetadata.
type EntVideoMetadataOrderField struct {
	// Value extracts the ordering value from the given EntVideoMetadata.
	Value    func(*EntVideoMetadata) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) entvideometadata.OrderOption
	toCursor func(*EntVideoMetadata) Cursor
}

// EntVideoMetadataOrder defines the ordering of EntVideoMetadata.
type EntVideoMetadataOrder struct {
	Direction OrderDirection              `json:"direction"`
	Field     *EntVideoMetadataOrderField `json:"field"`
}

// DefaultEntVideoMetadataOrder is the default ordering of EntVideoMetadata.
var DefaultEntVideoMetadataOrder = &EntVideoMetadataOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &EntVideoMetadataOrderField{
		Value: func(evm *EntVideoMetadata) (ent.Value, error) {
			return evm.ID, nil
		},
		column: entvideometadata.FieldID,
		toTerm: entvideometadata.ByID,
		toCursor: func(evm *EntVideoMetadata) Cursor {
			return Cursor{ID: evm.ID}
		},
	},
}

// ToEdge converts EntVideoMetadata into EntVideoMetadataEdge.
func (evm *EntVideoMetadata) ToEdge(order *EntVideoMetadataOrder) *EntVideoMetadataEdge {
	if order == nil {
		order = DefaultEntVideoMetadataOrder
	}
	return &EntVideoMetadataEdge{
		Node:   evm,
		Cursor: order.Field.toCursor(evm),
	}
}
