// Code generated by ent, DO NOT EDIT.

package ent

import (
	"com.gigaboo/clipserver/ent/entclipmetadata"
	"com.gigaboo/clipserver/ent/entvideometadata"
	"com.gigaboo/clipserver/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	entclipmetadataFields := schema.EntClipMetadata{}.Fields()
	_ = entclipmetadataFields
	// entclipmetadataDescFilename is the schema descriptor for filename field.
	entclipmetadataDescFilename := entclipmetadataFields[0].Descriptor()
	// entclipmetadata.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	entclipmetadata.FilenameValidator = entclipmetadataDescFilename.Validators[0].(func(string) error)
	// entclipmetadataDescFileURL is the schema descriptor for file_url field.
	entclipmetadataDescFileURL := entclipmetadataFields[1].Descriptor()
	// entclipmetadata.FileURLValidator is a validator for the "file_url" field. It is called by the builders before save.
	entclipmetadata.FileURLValidator = entclipmetadataDescFileURL.Validators[0].(func(string) error)
	// entclipmetadataDescFileSize is the schema descriptor for file_size field.
	entclipmetadataDescFileSize := entclipmetadataFields[2].Descriptor()
	// entclipmetadata.FileSizeValidator is a validator for the "file_size" field. It is called by the builders before save.
	entclipmetadata.FileSizeValidator = entclipmetadataDescFileSize.Validators[0].(func(int64) error)
	// entclipmetadataDescDuration is the schema descriptor for duration field.
	entclipmetadataDescDuration := entclipmetadataFields[3].Descriptor()
	// entclipmetadata.DurationValidator is a validator for the "duration" field. It is called by the builders before save.
	entclipmetadata.DurationValidator = entclipmetadataDescDuration.Validators[0].(func(int) error)
	// entclipmetadataDescFormat is the schema descriptor for format field.
	entclipmetadataDescFormat := entclipmetadataFields[4].Descriptor()
	// entclipmetadata.DefaultFormat holds the default value on creation for the format field.
	entclipmetadata.DefaultFormat = entclipmetadataDescFormat.Default.(string)
	entvideometadataFields := schema.EntVideoMetadata{}.Fields()
	_ = entvideometadataFields
	// entvideometadataDescFileSize is the schema descriptor for file_size field.
	entvideometadataDescFileSize := entvideometadataFields[2].Descriptor()
	// entvideometadata.FileSizeValidator is a validator for the "file_size" field. It is called by the builders before save.
	entvideometadata.FileSizeValidator = entvideometadataDescFileSize.Validators[0].(func(int64) error)
	// entvideometadataDescContentType is the schema descriptor for content_type field.
	entvideometadataDescContentType := entvideometadataFields[3].Descriptor()
	// entvideometadata.DefaultContentType holds the default value on creation for the content_type field.
	entvideometadata.DefaultContentType = entvideometadataDescContentType.Default.(string)
}
