// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EntClipMetadataColumns holds the columns for the "ent_clip_metadata" table.
	EntClipMetadataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "filename", Type: field.TypeString},
		{Name: "file_url", Type: field.TypeString},
		{Name: "file_size", Type: field.TypeInt64},
		{Name: "duration", Type: field.TypeInt},
		{Name: "format", Type: field.TypeString, Default: "mp4"},
		{Name: "word", Type: field.TypeString},
		{Name: "sentence", Type: field.TypeString},
		{Name: "thumbnail", Type: field.TypeString},
	}
	// EntClipMetadataTable holds the schema information for the "ent_clip_metadata" table.
	EntClipMetadataTable = &schema.Table{
		Name:       "ent_clip_metadata",
		Columns:    EntClipMetadataColumns,
		PrimaryKey: []*schema.Column{EntClipMetadataColumns[0]},
	}
	// EntVideoMetadataColumns holds the columns for the "ent_video_metadata" table.
	EntVideoMetadataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString, Unique: true},
		{Name: "filename", Type: field.TypeString},
		{Name: "file_size", Type: field.TypeInt64},
		{Name: "content_type", Type: field.TypeString, Default: "video/mp4"},
	}
	// EntVideoMetadataTable holds the schema information for the "ent_video_metadata" table.
	EntVideoMetadataTable = &schema.Table{
		Name:       "ent_video_metadata",
		Columns:    EntVideoMetadataColumns,
		PrimaryKey: []*schema.Column{EntVideoMetadataColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EntClipMetadataTable,
		EntVideoMetadataTable,
	}
)

func init() {
}
